name: ci

on:
  push:
    branches:
      - 'docker-publish'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      APP_URL: http://localhost:4000
      ENTITY_ID: https://saml.example.com/entityid
      PUBLIC_KEY: ''
      PRIVATE_KEY: ''
      NEXT_PUBLIC_GTM_ID: 'GTM-XXXXX'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: user/app:latest
