name: Build and Publish Docker

on:
  push:
    branches:
      - 'docker-publish'

jobs:
  next-build:
    runs-on: ubuntu-latest
    container: node:lts

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci

      - run: npm run build
        env:
          APP_URL: http://localhost:4000
          ENTITY_ID: https://saml.example.com/entityid
          PUBLIC_KEY: ''
          PRIVATE_KEY: ''
          NEXT_PUBLIC_GTM_ID: ''

      - name: Upload Next build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .next
            public
          retention-days: 1

  build-and-push-docker-image:
    needs: next-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download next build
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t kiranboxyhq/mock-saml:1.0 .
          docker push kiranboxyhq/mock-saml:1.0
